Fix dependabot login
Signed-off-by: Heba Elayoty <hebaelayoty@gmail.com>

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -49,24 +49,31 @@ jobs:
           echo "VERSION=${rand}" >> $GITHUB_ENV
           echo "CLUSTER_NAME=gpuprov${rand}" >> $GITHUB_ENV
 
+      - name: Install Azure CLI latest
+        run: |
+          if ! which az > /dev/null; then
+              echo "Azure CLI not found. Installing..."
+              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+          else
+              echo "Azure CLI already installed."
+          fi
+
       - uses: azure/login@v1.4.6
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           allow-no-subscriptions: true
 
-      - name: Install Azure CLI latest
-        run: |
-          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+      - name: Set subscription
+        run: az account set --subscription ${{secrets.SUBSCRIPTION_ID}}
 
-          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
-
-      - uses: azure/setup-helm@v3
+      - name: Install Helm
+        uses: azure/setup-helm@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
         id: install
 
-      - name: create ACR
+      - name: Create ACR
         shell: bash
         run: |
           make az-mkacr
@@ -79,7 +86,7 @@ jobs:
         run: |
           az identity create --name gpuIdentity --resource-group  ${{ env.CLUSTER_NAME }}
 
-      - name: build gpu-provisioner image
+      - name: Build gpu-provisioner image
         shell: bash
         run: |
           make docker-build
@@ -87,7 +94,7 @@ jobs:
           REGISTRY: ${{ env.CLUSTER_NAME }}.azurecr.io
           VERSION: ${{ env.VERSION }}
 
-      - name: create cluster
+      - name: Create cluster
         shell: bash
         run: |
           make az-mkaks
@@ -95,7 +102,6 @@ jobs:
           AZURE_RESOURCE_GROUP: ${{ env.CLUSTER_NAME }}
           AZURE_ACR_NAME: ${{ env.CLUSTER_NAME }}
           AZURE_CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
-
 
       - name: Install GPU-Provisioner helm chart
         shell: bash
